---
- name: iterates through subdirectories in non recursive manner and execute maven command
  hosts: localhost
  vars_files:
   - "./vars/default_vars.yml"
  vars:
   dirs: []
   filtered_dirs: []

  tasks:
   - name: list all directories in mentioned parent directory
     find:
      path: "{{ dir_path  }}"
      file_type: directory
      recurse: no
     register: output

   - name: print all listed directories captured in output
     no_log: true
     set_fact:
      dirs: "{{ dirs + [item.path] }}"
     with_items: "{{ output.files }}"

   #- debug: var=dirs

   - name: filter folders which does not have pom file
     no_log: true
     stat:
      path: "{{ item  }}/pom.xml"
     with_items: "{{ dirs }}"
     register: check_file_exists

   - name: extract filtered directories
     no_log: true
     set_fact:
      filtered_dirs: "{{ filtered_dirs + [item.stat.path] }}"
     with_items: "{{ check_file_exists.results  }} "
     when: item.stat.exists

   - name: execute mvn command
     command:
      chdir: "{{ item | dirname }}"
      cmd: "{{ mvn_command }}"
     with_items: "{{ filtered_dirs }}"
